### ISSUE TITLE
你好，关于dns TXT验证方式失败重试问题

### ISSUE THREAD

**Issue by toxmc** [shiny/HandyAcme#7]
交流下。
就是我有一个场景，首先域名证书是用dns TXT方式进行验证的。
首先是本地dns验证，验证通过后会到CA进行验证。由于dns TXT可能没有同步全球，CA去它的本地dns验证的时候发现没有相关TXT记录，导致验证失败。能否重新对该TXT记录进行验证。

**Comment by shiny** [comment]
这种情况下可以间隔几秒后，继续拉取 challenge 记录

- 如果是 pending / processing 状态可以不停轮询
- 如果是 valid 状态就进入下一步
- 如果是 invalid 基本就失败了，整个订单需要重来

可以参考 RFC 里的定义
<img width="457" alt="图片" src="https://github.com/shiny/HandyAcme/assets/117487/d063ef2b-f66a-48d4-9687-81b8d3af6cba">

也可以参考 ache.sh  的证书申请日志，首先设置 DNS 后会间隔几秒钟再发起验证；其次在你说的这种情况下它也会不断轮询。如果长时间一直通不过验证则超时失败。


RFC8555: Retrying Challenges https://datatracker.ietf.org/doc/html/rfc8555#section-8.2

**Comment by toxmc** [comment]
谢谢回复。是的，我这就是invalid状态，只能重来一次了。
